# Generated by Django 3.0.5 on 2020-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='id_barrio')),
                ('nombre', models.CharField(max_length=1000, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='id_ciudad')),
                ('nombre', models.CharField(max_length=1000, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id_comercio', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='id_comercio')),
                ('cuit', models.BigIntegerField(max_length=11, unique=True, verbose_name='cuit')),
                ('disponible', models.BooleanField(verbose_name='disponible')),
                ('razon_social', models.CharField(max_length=100, verbose_name='razon_social')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='id_entidad')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre')),
                ('iibb', models.BigIntegerField(max_length=15, verbose_name='iibb')),
                ('calle', models.CharField(max_length=100, verbose_name='calle')),
                ('numero', models.CharField(max_length=6, verbose_name='numero')),
                ('piso', models.CharField(max_length=100, null=True, verbose_name='piso')),
                ('departamento', models.CharField(max_length=10, null=True, verbose_name='departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='id_estado')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='id_pago')),
                ('monto', models.IntegerField(max_length=8, verbose_name='monto')),
                ('fecha_operacion', models.DateField(verbose_name='fecha_operacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='id_pais')),
                ('nombre', models.CharField(max_length=1000, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='id_pedido')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('validez', models.DateField(verbose_name='validez')),
                ('monto_total', models.IntegerField(max_length=8, verbose_name='monto_total')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='id_producto')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
                ('precio', models.IntegerField(max_length=8, verbose_name='precio')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.IntegerField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='id_transaccion')),
                ('medio_pago', models.CharField(max_length=50, verbose_name='medio_pago')),
                ('monto', models.IntegerField(max_length=8, verbose_name='monto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='id_usuario')),
                ('mail', models.CharField(max_length=80, verbose_name='mail')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha_nacimiento')),
                ('contraseña', models.CharField(max_length=50, verbose_name='contraseña')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='nacionalidad')),
            ],
        ),
    ]
